spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.194.139:3306/sso
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true